//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaCesfam2023.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CesfamClinicaEntities : DbContext
    {
        public CesfamClinicaEntities()
            : base("name=CesfamClinicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPRA> COMPRA { get; set; }
        public virtual DbSet<control_stock> control_stock { get; set; }
        public virtual DbSet<med_receta> med_receta { get; set; }
        public virtual DbSet<medicamento> medicamento { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<receta_med> receta_med { get; set; }
        public virtual DbSet<registro_retiro> registro_retiro { get; set; }
        public virtual DbSet<reserva_med> reserva_med { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
