//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaCesfam2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_stock
    {
        public int id_caduca_med { get; set; }
        public int medicamento_id_med { get; set; }
        public string descripcion { get; set; }
        public int cantidad { get; set; }
        public System.DateTime fecha_control { get; set; }
        public string usuario_rut_user { get; set; }
    
        public virtual medicamento medicamento { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
