//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaCesfam2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class med_receta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public med_receta()
        {
            this.registro_retiro = new HashSet<registro_retiro>();
            this.reserva_med = new HashSet<reserva_med>();
        }
    
        public int id_med_recet { get; set; }
        public int receta_med_id_receta { get; set; }
        public int medicamento_id_med { get; set; }
        public int cantidad { get; set; }
        public string retiro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registro_retiro> registro_retiro { get; set; }
        public virtual medicamento medicamento { get; set; }
        public virtual receta_med receta_med { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva_med> reserva_med { get; set; }
    }
}
